### ISSUE TITLE
The model always seems to be unloaded, even if I have false selected in the unload option

### ISSUE THREAD

**Issue by WainWong** [Nojahhh/ComfyUI_GLM4_Wrapper#2]
I'm using glm 4v.The model always seems to be unloaded，When multiple images need to be processed consecutively, a lot of time is spent on loading the model, resulting in a very slow

**Comment by Nojahhh** [comment]
Noted. Because of Comfy memory management I will have to rebuild model loading using a pipeline.

Working on it now and will update soon.

**Comment by Nojahhh** [comment]
Fixed in latest update. Models now loaded through pipeline and will stay loaded if not unload_model is true.

Please update the repo or reinstall it.
