### ISSUE TITLE
GLM4Inference.infer() got an unexpected keyword argument 'max__new_tokens'

### ISSUE THREAD

**Issue by cheezecrisp** [Nojahhh/ComfyUI_GLM4_Wrapper#7]
When running the glm-4-inference.json workflow, got following error:

got prompt
!!! Exception during processing !!! GLM4Inference.infer() got an unexpected keyword argument 'max__new_tokens'
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GLM4Inference.infer() got an unexpected keyword argument 'max__new_tokens'

Prompt executed in 0.11 seconds

**Comment by Nojahhh** [comment]
Thank you for reporting this. It was a typo in the inference nodes from the last update.
It's fixed now, please update the wrapper and it should be working as intended.

**Comment by cheezecrisp** [comment]
> Thank you for reporting this. It was a typo in the inference nodes from the last update. It's fixed now, please update the wrapper and it should be working as intended.

Thank you, it works now! BTW, so far as I know those LLM prompt enhance/image caption usally use a random seed and give out different result by different seed. But this node dose not have a seed and the result will not change as long as the input remains the same. Is it possible to make the result variable?

**Comment by Nojahhh** [comment]
Glad to hear its working!

Yes, I'm currently working on changing the structure for inferencing with the gptq models to make them run even faster.
I will look at implementing manual seeds during that update as well.

**Comment by cheezecrisp** [comment]
> Glad to hear its working!
> 
> Yes, I'm currently working on changing the structure for inferencing with the gptq models to make them run even faster. I will look at implementing manual seeds during that update as well.

Looking forward to it.

**Comment by Nojahhh** [comment]
@cheezecrisp Just added seed to the nodes. Try it out if you like!

**Comment by cheezecrisp** [comment]
> @cheezecrisp Just added seed to the nodes. Try it out if you like!

Oh yeah sure it works, appreciate for your great effort!
